function byId(id) {
  const element = document.getElementById(id);
  if (!element) throw new Error(`Missing required element #${id}`);
  return element;
}

export const elements = {
  searchForm: byId("searchForm"),
  zipInput: byId("zipInput"),
  useLocationButton: byId("useLocationButton"),
  locationStatus: byId("locationStatus"),
  radiusInput: byId("radiusInput"),
  radiusStatus: byId("radiusStatus"),
  startDateInput: byId("startDateInput"),
  endDateInput: byId("endDateInput"),
  theatreMeta: byId("theatreMeta"),
  theatreStatus: byId("theatreStatus"),
  theatreInput: byId("theatreInput"),
  theatreMenu: byId("theatreMenu"),
  movieGroup: byId("movieGroup"),
  movieMeta: byId("movieMeta"),
  movieStatus: byId("movieStatus"),
  movieInput: byId("movieInput"),
  movieMenu: byId("movieMenu"),
  formatOptions: byId("formatOptions"),
  formatMeta: byId("formatMeta"),
  formatStatus: byId("formatStatus"),
  formatGuide: byId("formatGuide"),
  formatGuideButton: byId("formatGuideButton"),
  formatGuideContent: byId("formatGuideContent"),
  startTimeInput: byId("startTimeInput"),
  endTimeInput: byId("endTimeInput"),
  adjacentSeatsInput: byId("adjacentSeatsInput"),
  excludeAccessibleInput: byId("excludeAccessibleInput"),
  preferencesGroup: byId("preferencesGroup"),
  seatPreferenceHelp: byId("seatPreferenceHelp"),
  seatPreferenceGrid: byId("seatPreferenceGrid"),
  editSeatGridButton: byId("editSeatGridButton"),
  selectCenterGridButton: byId("selectCenterGridButton"),
  clearGridButton: byId("clearGridButton"),
  cancelSeatGridButton: byId("cancelSeatGridButton"),
  doneSeatGridButton: byId("doneSeatGridButton"),
  gridStatus: byId("gridStatus"),
  searchButton: byId("searchButton"),
  summary: byId("summary"),
  resultsToolbar: byId("resultsToolbar"),
  sortInput: byId("sortInput"),
  sortStatus: byId("sortStatus"),
  results: byId("results"),
  pagination: byId("pagination"),
};
